theme: jekyll-theme-minimal
description: >
    A collection of my math related programs and
    manuscripts which I find interesing enough to
    show to the world.
    [![DONATE](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.me/lucahappel)
logo: https://github.com/Quoteme/math/raw/master/social_preview.png?raw=true
